#!/usr/bin/env ruby

begin
  name = File.read("bin/config")
  abort if !name

  # Create a final commit
  system("git add . && git commit --allow-empty -m \"Final commit\"")

  # Push the changes to the remote repository
  system("git push origin #{name}")

  # Bundle changes into a Git bundle file
  system("git bundle create ../#{name}.bundle HEAD #{name}")
rescue SystemExit
  puts "File must be run as `ruby bin/end <your-name>`"
end
