#!/usr/bin/env ruby

begin
  name = ARGV.first
  abort if !name

  File.write("bin/config", name)

  # Clone the Git repository
  system("git clone https://github.com/johnkiguma/phase-1-code-challenge-flatabeer.git code-challenge")

  # Change to the code-challenge directory
  system("cd code-challenge")

  # Create a new branch with the provided name
  system("git checkout -b #{name}")

  # Make an initial commit
  system("git commit --allow-empty -m \"Initial commit\"")

  puts "Removing code-challenge"
  system("rm -rf ../code-challenge")
rescue SystemExit
  puts "File must be run as `ruby bin/start <your-name>`"
end
